discovery:
  server:
    port: 8070
    hostName: 18.225.21.42

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${discovery.server.hostName}:${discovery.server.port}/eureka'
    region: us-east-2
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    ip-address: 18.118.73.177
    hostname: 18.118.73.177
    #non-secure-port: 9096

logging:
  file:
    name: '/home/ubuntu/scanner-logs/scanner-app-prod.log'
  level:
    root: info

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'

database:
  host: '84.32.41.139'
  port: 3306
  db-name: toyscanner_db

spring:
  datasource:
    url: 'jdbc:mysql://${database.host}:${database.port}/${database.db-name}?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
    username: root
    password: 14292Scanner
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: false
      validation-query: SELECT 1
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 52.44.140.170
    port: 6967
    cache:
      redis:
        time-to-live: 1200000
      cache-names: SCANNER